### ISSUE TITLE
Error on fetching fields

### ISSUE THREAD

**Issue by annared** [MhdSyrwan/aor-embedded-array#1] opened 2017-09-20 10:57 UTC
Hi, 
first of all thanks for this project. This is just what i need.

I have a mongoose document with a nested field:
```
var WorkSchema = new Schema({
  title: { type: String },
  description: { type: String },
  links: [{ 
    title: { type: String },
    url: { type: String },
  }],
},{ toObject: { virtuals: true },  toJSON: { virtuals: true }}, { versionKey: false });
```

i'm using your library to insert links inside this document:

```
<EmbeddedArrayInput source="links">
   <TextInput label="URL" source="url" />
   <TextInput label="Title" source="title"/>
</EmbeddedArrayInput>
```

I can create links without problem but when i try to fetch the fields are empty (but they exist in the database), the number of embeddedarray is correct: if i have two links in the database i have two embeddedarray in the aor edit page.
 this is the error on the console: query option is required. You must specify your GraphQL document in the query option.

**Comment by MhdSyrwan** [comment] 2017-09-20 11:17
Can you please post the json output for this collection ?

**Comment by annared** [comment] 2017-09-20 11:58
This is what the resolver return:

```
{ state: 'unpublish',
  title: 'qweewqweqewq',
  __v: 0,
  links: 
   [ { url: 'asdasdasd',
       title: 'asddasdsa',
       _id: 59c248ebce3696023ef84532 } ],
  id: 59c248ebce3696023ef84531 }
```

and this is the response (from the network inspector):
```
{"id":"59c248ebce3696023ef84531",
"title":"qweewqweqewq",
"description":null,
"links":["{ _id: 59c248ebce3696023ef84532,\n  title: 'asddasdsa',\n  url: 'asdasdasd'}"],
"__typename":"Work"}}
```

**Comment by MhdSyrwan** [comment] 2017-09-20 12:00
what do you mean by the resolver ?

**Comment by MhdSyrwan** [comment] 2017-09-20 12:02
can you please try this 
```jsx
<EmbeddedArrayInput source="links">
   <TextInput label="URL" source="url" />
   <TextInput label="Title" source="title"/>
   <TextInput label="Debug" source="length"/>
</EmbeddedArrayInput>
```

what do you see in the field "Debug"

**Comment by annared** [comment] 2017-09-20 12:05
i'm using admin on rest with graphql, resolvers are functions to execute queries

**Comment by annared** [comment] 2017-09-20 12:06
the debug field returns "75"

**Comment by MhdSyrwan** [comment] 2017-09-20 12:17
that's just what I've expected. You've an issue in your graphql configuration. it's printing the array as a string.

**Comment by MhdSyrwan** [comment] 2017-09-20 12:19
It might be a bug in admin-on-rest graphql adapter. or it doesn't support the embedded array at all.

**Comment by Phocea** [comment] 2017-09-20 12:25
Just my 2 cents, but with a JSON looking like:

**Comment by annared** [comment] 2017-09-20 12:38
Solved it! Thanks.

but i still get this error in the console: query option is required. You must specify your GraphQL document in the query option.

**Comment by Phocea** [comment] 2017-09-20 12:41
Just my 2 cents, but with a JSON looking like:

` {
   "id":"r_profile_534534",
   "name":"534534 Profile access Role",
   "description":"Role to access user's own profile",
   "permissions":[
      {
         "businessDomain":"admin:users",
         "authorizations":"read,write"
      }
   ],
   "creationDate":"2017-09-19T14:14:16Z",
   "lastModificationDate":"2017-09-19T14:14:16Z"`

and a config looking like:
`  <EmbeddedArrayInput source="permissions">
          <TextInput source="businessDomain" label="resources.roles.businessDomain"/>
          <TextInput source="authorizations" label="resources.roles.authorizations"/>   </EmbeddedArrayInput>`

It works as advertised

**Comment by MhdSyrwan** [comment] 2017-09-20 12:46
@annared I think you need to contact graphql repo maintainers for that warning.

**Comment by MhdSyrwan** [comment] 2017-09-20 13:01
I'm closing this since the issue is resolved.

**Closed by MhdSyrwan** 2017-09-20 13:01 UTC
