### ISSUE TITLE
Alignment issue using ReferenceInput

### ISSUE THREAD

**Issue by ashimsaha2311** [MhdSyrwan/aor-embedded-array#4] opened 2017-09-29 16:07 UTC
I am getting alignment issue when I use ReferenceInput,
The code is as follows
```jsx
    <Create {...props}>
        <TabbedForm>
            <FormTab label="Details">
                <TextInput source="id" />
                <TextInput source="name" />
                <TextInput source="details" />
                <TextInput source="date" />
                <TextInput source="duration" />
                <TextInput source="time" />
                <ReferenceInput source="id" reference="standards" allowEmpty>
                    <SelectInput source="name" />
                </ReferenceInput>
            </FormTab>
            <FormTab label="Subjects">
                <EmbeddedArrayInput source="subjects">
                    <ReferenceInput label="Enter subject" source="subject_id" reference="subjects" allowEmpty style={{ display: 'inline-block' }} >
                        <SelectInput source="name" />
                    </ReferenceInput>
                    <NumberInput label="Enter full marks" source="fullMarks" style={{ display: 'inline-block' }} />
                    <NumberInput label="Enter pass marks" source="passMarks" style={{ display: 'inline-block' }} />
                </EmbeddedArrayInput>
            </FormTab>
        </TabbedForm>
    </Create>
```

Output
![image](https://user-images.githubusercontent.com/32305652/31024883-17692ba8-a55e-11e7-88d8-18bddba1a37e.png)

**Comment by MhdSyrwan** [comment] 2017-09-29 19:48
Does this issue gets resolved if you remove the `{ display: 'inline-block' }` ?

**Comment by ashimsaha2311** [comment] 2017-09-30 07:01
After removing `{ display: 'inline-block' }` from `<ReferenceInput label="Enter subject" source="subject_id" reference="subjects" allowEmpty style={{ display: 'inline-block' }} >`. then I got something like

![image](https://user-images.githubusercontent.com/32305652/31043525-1a16827e-a5db-11e7-800a-d6b5faa6f46a.png)

But it is better to have inline

**Comment by ashimsaha2311** [comment] 2017-09-30 07:16
After some experiment when I use `{display: 'inline-block', float: 'left'}`
```jsx

    <Create {...props}>
        <TabbedForm>
            <FormTab label="Details">
                <TextInput source="id" />
                <TextInput source="name" />
                <TextInput source="details" />
                <TextInput source="date" />
                <TextInput source="duration" />
                <TextInput source="time" />
                <ReferenceInput source="id" reference="standards" allowEmpty>
                    <SelectInput source="name" />
                </ReferenceInput>
            </FormTab>
            <FormTab label="Subjects">
                <EmbeddedArrayInput source="subjects">
                    <ReferenceInput label="Enter subject" source="subject_id" reference="subjects" allowEmpty style={{ display: 'inline-block', float: 'left' }} >
                        <SelectInput source="name" />
                    </ReferenceInput>
                    <NumberInput label="Enter full marks" source="fullMarks" style={{ display: 'inline-block', float: 'left', marginLeft: '20px' }} />
                    <NumberInput label="Enter pass marks" source="passMarks" style={{ display: 'inline-block', float: 'left', marginLeft: '20px' }} />
                </EmbeddedArrayInput>
            </FormTab>
        </TabbedForm>
    </Create>
```
Then it gives me correct as below
![image](https://user-images.githubusercontent.com/32305652/31043653-61ed7d4e-a5dd-11e7-97b0-92bb555cc83f.png)

**Comment by MhdSyrwan** [comment] 2017-10-05 15:19
Closing since it's caused by modifications from your side. It's a normal css issue in application layer.

Feel free to re-open if you it appears without modifying elements' style manually.

**Closed by MhdSyrwan** 2017-10-05 15:19 UTC
