### ISSUE TITLE
labelAdd and labelRemove are not working

### ISSUE THREAD

**Issue by mywebstuff** [MhdSyrwan/aor-embedded-array#8] opened 2017-10-10 13:34 UTC
Hi!

First off, let me thank you, this is a lifesaver plugin :)

However, for me the labellAdd and labelRemove props are not working, or at least I'm missing something.

Example code:
```
export const CreateTest = (props) => (
  <Create {...props}>
    <TabbedForm>
      <FormTab label="Testing">
        <EmbeddedArrayInput source="testarr" label="Tests" labelAdd="Add new test" labelRemove="Remove test"
          <TextInput source="name">
        </EmbeddedArrayInput>
      </FormTab >
    </TabbedForm>
  </Create>
);
```
So I added the labelAdd and labelRemove props but the buttons labels are still 'Add' and 'Remove' respectively. Am I missing something here?

**Comment by MhdSyrwan** [comment] 2018-03-16 08:18
I'm very sorry for not replying here, I couldn't find the time check this.
Most probably the problem is happening because the `labelAdd` prop is not being passed to the internal rendering method `renderList` as shown below.

https://github.com/MhdSyrwan/aor-embedded-array/blob/master/src/mui/input/EmbeddedArrayInput.js#L193

I will try to work on this soon, i want to write a failing test case first then to implement the solution to make sure everything is OK.

**Comment by MhdSyrwan** [comment] 2018-03-17 22:06
I was totally wrong, This part was done by another contributer in the original PR which this library is created from.

both `labelAdd` and `labelRemove` are supposed to be a translation path. Their default values are: `aor.input.embedded_array.add` and `aor.input.embedded_array.remove`.

To change these labels, you have either to set values for the default translation paths or to create new ones and provide their paths as `labelAdd` and `labelRemove`.

**Comment by MhdSyrwan** [comment] 2018-03-18 15:40
A new section has been added to the `README` file to explain about this feature.

I'm closing this issue for now, please re-open if you are still facing an issue.

**Closed by MhdSyrwan** 2018-03-18 15:40 UTC
